<?php

namespace Drupal\labs_custom_blocks\Access;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeAccessControlHandler;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\node\NodeGrantDatabaseStorageInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;

class LabsNodeAccess extends NodeAccessControlHandler {
  /**
   *
   * @var object $userSitesInfo
   */
  protected object $userSitesInfo;

  /**
   * Constructs a NodeAccessControlHandler object.
   *
   * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
   *   The entity type definition.
   * @param \Drupal\node\NodeGrantDatabaseStorageInterface $grant_storage
   *   The node grant storage.
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager
   *   The entity type manager.
   */
  public function __construct(EntityTypeInterface $entity_type, NodeGrantDatabaseStorageInterface $grant_storage, EntityTypeManagerInterface $entity_type_manager, $userSitesInfo) {
    parent::__construct($entity_type, $grant_storage, $entity_type_manager);
    $this->userSitesInfo = $userSitesInfo;
  }

  public static function createInstance(ContainerInterface $container, EntityTypeInterface $entity_type): LabsNodeAccess|NodeAccessControlHandler|static {
    return new static(
      $entity_type,
      $container->get('node.grant_storage'),
      $container->get('entity_type.manager'),
      $container->get('labs_custom_blocks.get_user_site_info')
    ); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  protected function checkAccess(EntityInterface $entity, $operation, AccountInterface $account) {
    $access = parent::checkAccess($entity, $operation, $account);
    if (\Drupal::currentUser()->isAuthenticated() && !\Drupal::currentUser()->hasRole('administrator') && ($entity instanceof NodeInterface)) {
      if ($operation == 'view')  {
        return $access;
      } else {
        $access = AccessResult::forbidden();
        $current_user_term_ids = $this->userSitesInfo->getCurrentUserTermIds();
        $entity_term_ids = $this->userSitesInfo->getCurrentEntityTermIds($entity);
        if ($this->userSitesInfo->canEdit($current_user_term_ids, $entity_term_ids) === TRUE) {
          $access = AccessResult::neutral();
          // revision tab not showing up using AccessResult::neutral() somehow, so we force it to show when user has permission.
          if ($operation == 'view all revisions') {
            return AccessResult::allowed();
          }
        }
        $access->addCacheableDependency($account);
        $access->addCacheableDependency($entity);
        return $access;
      }
    }
    return $access; // TODO: Change the autogenerated stub
  }
}
