<?php

namespace Drupal\labs_custom_blocks\Access;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\media\MediaAccessControlHandler;
use Drupal\media\MediaInterface;
use Drupal\node\NodeGrantDatabaseStorageInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class LabsMediaAccess extends MediaAccessControlHandler {
  /**
   *
   * @var object $userSitesInfo
   */
  protected object $userSitesInfo;

  /**
   *
   * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
   *   The entity type definition.
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager
   *   The entity type manager.
   */
  public function __construct(EntityTypeInterface $entity_type, EntityTypeManagerInterface $entity_type_manager, $userSitesInfo) {
    parent::__construct($entity_type, $entity_type_manager);
    $this->userSitesInfo = $userSitesInfo;
  }

  public static function createInstance(ContainerInterface $container, EntityTypeInterface $entity_type) {
    return new static(
      $entity_type,
      $container->get('entity_type.manager'),
      $container->get('labs_custom_blocks.get_user_site_info')
    ); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  protected function checkAccess(EntityInterface $entity, $operation, AccountInterface $account) {
    $access = parent::checkAccess($entity, $operation, $account);
    if (\Drupal::currentUser()->isAuthenticated() && !\Drupal::currentUser()->hasRole('administrator') && ($entity instanceof MediaInterface)) {
      if ($operation == 'view') {
        return $access;
      } else {
        $access = AccessResult::forbidden();
        $current_user_term_ids = $this->userSitesInfo->getCurrentUserTermIds();
        $entity_term_ids = $this->userSitesInfo->getCurrentEntityTermIds($entity);
        if ($this->userSitesInfo->canEdit($current_user_term_ids, $entity_term_ids) === TRUE) {
          $access = AccessResult::allowed();
        }
        $access->addCacheableDependency($account);
        $access->addCacheableDependency($entity);
        return $access;
      }
    }
    return $access; // TODO: Change the autogenerated stub
  }
}
