<?php

namespace Drupal\labs_custom_blocks\Access;

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityHandlerInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\system\MenuAccessControlHandler;
use Drupal\system\MenuInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class LabsMenuAccess extends MenuAccessControlHandler implements EntityHandlerInterface {

  /**
   *
   * @var object $userSitesInfo
   */
  protected object $userSitesInfo;

  /**
   *
   * @var EntityTypeManagerInterface $entityTypeManager
   */
  protected EntityTypeManagerInterface $entityTypeManager;

  public function __construct(EntityTypeInterface $entity_type, EntityTypeManagerInterface $entityTypeManager, $userSitesInfo) {
    parent::__construct($entity_type);
    $this->entityTypeManager = $entityTypeManager;
    $this->userSitesInfo = $userSitesInfo;
  }

  public static function createInstance(ContainerInterface $container, EntityTypeInterface $entity_type): LabsMenuAccess|MenuAccessControlHandler|static {
    return new static(
      $entity_type,
      $container->get('entity_type.manager'),
      $container->get('labs_custom_blocks.get_user_site_info')
    ); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  protected function checkAccess(EntityInterface $entity, $operation, AccountInterface $account) {

    // prevent menu from being deleted if the term exists
    if ($entity instanceof MenuInterface) {
      if ($operation == 'delete') {
        $menu_label = $entity->label();
        $term_entity = $this->entityTypeManager->getStorage('taxonomy_term')->loadByProperties(['name' => $menu_label]);
        if (!empty($term_entity)) {
          return AccessResult::forbidden();
        }
      }
    }


    // Deny access when the operation is edit/delete
    if (\Drupal::currentUser()->isAuthenticated() && !\Drupal::currentUser()->hasRole('administrator') && $entity instanceof MenuInterface) {
      $access = AccessResult::forbidden();
      $current_user_term_ids = $this->userSitesInfo->getCurrentUserTermIds();
      $current_user_term_labels = array();
      foreach ($current_user_term_ids as $id) {
        $current_user_term_labels[] = $this->entityTypeManager->getStorage('taxonomy_term')->load($id)->label();
      }
      $entity_label = $entity->label();
      if (in_array($entity_label, $current_user_term_labels) && $operation != 'delete') {
        $menu_label = $entity->label();
        $term_entity = $this->entityTypeManager->getStorage('taxonomy_term')->loadByProperties(['name' => $menu_label]);
        if (empty($term_entity)) {
          $access = AccessResult::forbidden();
        } else {
          $access = AccessResult::allowed();
        }
      }
      $access->addCacheableDependency($account);
      $access->addCacheableDependency($entity);
    } else {
      $access = parent::checkAccess($entity, $operation, $account);
    }
    return $access; // TODO: Change the autogenerated stub
  }
}
