<?php
/**
 * User: cheng chen
 * Date: 12/12/19
 * Time: 3:44 PM
 */

namespace Drupal\webform_to_node\Plugin\WebformHandler;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Plugin\WebformHandlerBase;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\node\Entity\Node;

/**
 * Form submission handler.
 *
 * @WebformHandler(
 *   id = "event_webform_to_node",
 *   label = @Translation("Event Details webform submission converter"),
 *   category = @Translation("Form Handler"),
 *   description = @Translation("Convert webform submissions to nodes"),
 *   cardinality =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::CARDINALITY_SINGLE,
 *   results =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::RESULTS_PROCESSED,
 * )
 */
class EventDetailsSubmissionConverterHandler extends WebformHandlerBase {

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */


  public function submitForm(array &$form, FormStateInterface $form_state, WebformSubmissionInterface $webform_submission) {

  $field_title = $form_state->getValue('title');
  $field_event_details_subtitle = $form_state->getValue('event_subtitle');
  $field_event_details_event_type = $form_state->getValue('event_type');
  $field_event_details_time_zone = $form_state->getValue('time_zone');
  $field_event_details_location = $form_state->getValue('event_location');
  $field_event_details_address = $form_state->getValue('event_address');
  $field_event_details_sponsor = $form_state->getValue('event_sponsor');
  $field_event_details_speakers = $form_state->getValue('event_speakers');
  $field_event_details_description = $form_state->getValue('event_description');
  $field_event_start_date = $form_state->getValue('event_date_range1')[0]['start'];
  $event_start_date = str_replace("+0000", "", $field_event_start_date);
  $field_event_end_date = $form_state->getValue('event_date_range1')[0]['end'];
  $event_end_date = str_replace("+0000", "", $field_event_end_date);

  // Get the summary and link details from the form.
  $field_event_details_description_summary = $form_state->getValue('event_description_summary');
  $field_event_details_link_title = $form_state->getValue('event_link')['title'];
  $field_event_details_link_url = $form_state->getValue('event_link')['url'];

  // Prepare the body text and summary for the node.
  $body_text = $field_event_details_description; // Main body text
  $summary_text = $field_event_details_description_summary; // Summary text

  // Prepare the link field.
  $field_event_details_link = [
    'title' => $field_event_details_link_title,
    'uri' => $field_event_details_link_url,
  ];

  
  $values = [
    'title' => $field_title,
    'field_event_details_subtitle' => $field_event_details_subtitle,
    'field_event_details_event_type' => $field_event_details_event_type,
    'field_event_details_time_zone' => $field_event_details_time_zone,
    'field_event_details_location' => $field_event_details_location,
    'field_event_details_address' => $field_event_details_address,
    'field_event_details_sponsor' => $field_event_details_sponsor,
    'field_event_details_speakers' => $field_event_details_speakers,
    'field_event_details_description' => [ 
      'value' => $body_text,
      'summary' => $summary_text, 
      'format' => 'full_html', 
    ],
    'field_event_details_link' => $field_event_details_link,
    'field_event_details_date_range' => [
      'value'=> $event_start_date,
      'end_value' => $event_end_date,
    ]
  ];

  // Create the node.
  $node = Node::create([
    'type' => 'event_details', 
    'langcode' => 'en',
    'uid' => 1, 
    'status' => 0, 
  ]);

  // Set the values for the node.
  foreach ($values as $key => $value) {
    $node->set($key, $value);
  }

  // Save the node.
  $result = $node->save();
  if ($result !== 1) {
    \Drupal::logger('webform_to_node')->error('Webform submission to node conversion has failed');
  } else {
    \Drupal::logger('webform_to_node')->info('@title has been created via a webform submission', ['@title' => $field_title]);
  }
}
}