<?php
/**
 * User: cheng chen
 * Date: 12/12/19
 * Time: 3:44 PM
 */

namespace Drupal\webform_to_node\Plugin\WebformHandler;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Plugin\WebformHandlerBase;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\node\Entity\Node;

/**
 * Form submission handler.
 *
 * @WebformHandler(
 *   id = "research_webform_to_node",
 *   label = @Translation("Research Project webform submission converter"),
 *   category = @Translation("Form Handler"),
 *   description = @Translation("Convert webform submissions to nodes"),
 *   cardinality =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::CARDINALITY_SINGLE,
 *   results =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::RESULTS_PROCESSED,
 * )
 */
class ResearchProjectSubmissionConverterHandler extends WebformHandlerBase {

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state, WebformSubmissionInterface $webform_submission) {


    $title = $form_state->getValue('project_name');
    $field_advisor_email_research_pro = $form_state->getValue('advisor_email_address');
    $field_advisor_dept_research_pro = $form_state->getValue('advisor_department');
    $field_advisor_name_research_proj = $form_state->getValue('advisor_full_name');
    $field_advisor_phone_research_pro = $form_state->getValue('advisor_phone_number');
    $field_description_research_pro = $form_state->getValue('full_html');
    $field_research_pro_keywords = $form_state->getValue('project_keywords');
    $field_research_pro_stipend = $form_state->getValue('project_stipend');
    $field_summary_research_pro = $form_state->getValue('project_summary');
    $field_research_pro_types = $form_state->getValue('project_type');
    $field_advisor_bio_research_pro = $form_state->getValue('biography_link');
    $field_research_pro_location = $form_state->getValue('primary_research_location');


    $values = array(
      'field_advisor_email_research_pro' => $field_advisor_email_research_pro,
      'field_advisor_dept_research_pro' => $field_advisor_dept_research_pro,
      'field_advisor_name_research_proj' => $field_advisor_name_research_proj,
      'field_advisor_phone_research_pro' => $field_advisor_phone_research_pro,
      'field_description_research_pro' => $field_description_research_pro,
      'field_research_pro_keywords' => $field_research_pro_keywords,
      'field_research_pro_stipend' => $field_research_pro_stipend,
      'field_summary_research_pro' => $field_summary_research_pro,
      'field_research_pro_types' => $field_research_pro_types,
      'field_advisor_bio_research_pro' => $field_advisor_bio_research_pro,
      'field_research_pro_location' => $field_research_pro_location
    );

    $content_type = 'research_projects';
    $title = $title;
    $langcode = 'en';
    $uid = 1; // superuser
    $status = 0; // unpublish them by default
    // all the variables and their mapping up to this point can be set in the handler config form if needed in future.

    $node = Node::create(array(
        'type' => $content_type,
        'title' => $title,
        'langcode' => $langcode,
        'uid' => $uid,
        'status' => $status,
    ));

    foreach ($values as $key => $value) {
        $node->set($key, $value);
    }

    $result = $node->save();
    if ($result !== 1) {
      \Drupal::logger('webform_to_node')->error('Webform submission to node convertion has failed');
    } else {
      \Drupal::logger('webform_to_node')->info('@title has been created via a webform submission', ['@title' => $title]);
    }
  }
}
