<?php

/**
 * @file
 * Contains ccedit.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

// Use statements to support hook_entity_field_access.
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Access\AccessResult;

// Interfaces used by entities to declare "ownership".
use Drupal\user\EntityOwnerInterface;
use Drupal\user\UserInterface;

// Use statements for hook_entity_test_access.
use Drupal\Core\Entity\EntityInterface;


use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_help().
 */
function ccedit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ccedit module.
    case 'help.page.ccedit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('let cc edit that page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_node_access_records().
 */
//function ccedit_node_access_records(\Drupal\node\NodeInterface $node)
//{
////    $is_node = \Drupal::routeMatch()->getParameter('node');
//    $grants = array();
//
////    kint($is_node);
////    exit;
//
////if($is_node) {
//
//    $node_tags = array();
////    $user_tags = array();
//  if(is_object($node->field_biography_drupal_site_ref) && method_exists($node->field_biography_drupal_site_ref, count)) {
//    $node_tag_count = $node->field_biography_drupal_site_ref->count();
//
//    //    print($node_tag_count);
//
//    for ($i = 0; $i < $node_tag_count; $i++) {
//      $tid = $node->field_biography_drupal_site_ref[$i]->target_id;
//      $grants[] = [
//        'realm' => 'ccedit_realm',
//        'gid' => $tid,
//        'grant_view' => 1,
//        'grant_update' => 1,
//        'grant_delete' => 0,
//        'priority' => 1,
//      ];
//    }
//
//    $grants[] = [
//      'realm' => 'ccedit_realm',
//      'gid' => 0,
//      'grant_view' => 1,
//      'grant_update' => 0,
//      'grant_delete' => 0,
//      'priority' => 0,
//    ];
//    return $grants;
//  }
//}

/**
 * Implements hook_node_grants().
 */
//function ccedit_node_grants(\Drupal\Core\Session\AccountInterface $account, $op)
//{
//    $grants = array();
//
//    $uid = $account->id();
//
//    $user = \Drupal\user\Entity\User::load($uid); // Drupal 9 compatible
//    $user_tag_count = $user->field_laopo->count();
//
////    print($user_tag_count);
//
//    for ($i = 0; $i < $user_tag_count; $i++) {
//        $tid = $user->field_laopo[$i]->target_id;
//        $grants['ccedit_realm'][] = $tid;
//    }
//
//    $grants['ccedit_realm'][] = 0;
//
//    return $grants;
//}

/**
 * Implements hook_entity_field_access().
 */
function ccedit_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
//kint($operation);
  if ($operation == 'edit' && $field_definition->getName() == 'field_biography_drupal_site_ref') {
    return AccessResult::allowed();
  } elseif ($operation == 'edit' && $field_definition->getName() != 'field_biography_drupal_site_ref') {
    $uid = $account->id();
    $user = \Drupal\user\Entity\User::load($uid); // Drupal 9 compatible
    $user_terms_count = $user->field_user_term->count();
    for ($i = 0; $i < $user_terms_count; $i++) {
      $user_terms[] = $user->field_user_term[$i]->target_id;
    }

    if ($user_terms_count == 0) {
      return AccessResult::allowed();
    }
//    kint($user_terms);

    $node = \Drupal::routeMatch()->getParameter('node');
    $node_terms = [];
    if (is_object($node) && method_exists($node->field_biography_drupal_site_ref, 'count')) {
      $node_terms_count = $node->field_biography_drupal_site_ref->count();
      if ($node instanceof \Drupal\node\NodeInterface) {
        // You can get nid and anything else you need from the node object.
        for ($i = 0; $i < $node_terms_count; $i++) {
          $node_terms[] = $node->field_biography_drupal_site_ref[$i]->target_id;
        }
      }
      $user_terms_array = array();
      $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadMultiple($user_terms);
      foreach($terms as $term) {
        $user_terms_array[] = $term->label();
      }
      $user_terms_string = implode(", ", $user_terms_array);
      $access = 0;
      foreach ($node_terms as $node_term) {
        if (in_array($node_term, $user_terms)) {
          $access = 1;
        }
      }
      if($access == 1) {
        return AccessResult::neutral();
      } else {
        $message = [
          '#theme' => 'item_list',
          '#list_type' => 'ul',
          '#title' => 'You only have full editing permission on the following site(s): ',
          '#items' => $user_terms_array,
        ];
        drupal_set_message($message, 'warning');
        return AccessResult::forbidden('sorry you do not have permission to edit this field');
      }
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ccedit_form_node_biography_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = '_ccedit_form_node_biography_edit_form_validate';
}

function _ccedit_form_node_biography_edit_form_validate(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if (!empty($form['field_biography_drupal_site_ref']['widget']['target_id']['#default_value'])) {
    $term_ids = array();
    $term_ids_amount = count($form['field_biography_drupal_site_ref']['widget']['target_id']['#default_value']);
    for ($i=0; $i<$term_ids_amount; $i++) {
      $term_ids[] = $form['field_biography_drupal_site_ref']['widget']['target_id']['#default_value'][$i]->id();
    }

    $uid = Drupal::currentUser()->id();
    $user = \Drupal\user\Entity\User::load($uid); // Drupal 9 compatible

    $user_terms_count = $user->field_user_term->count();
    for ($i = 0; $i < $user_terms_count; $i++) {
      $user_terms[] = $user->field_user_term[$i]->target_id;
    }

    $user_terms_name = array();
    $user_terms_label = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadMultiple($user_terms);
    foreach($user_terms_label as $user_term_label) {
      $user_terms_name[] = $user_term_label->label();
    }
    $user_terms_string = implode(", ", $user_terms_name);

    kint($form_state);

    $websites_field_updates_string = $form_state->getUserInput()['field_biography_drupal_site_ref']['target_id'];
    $websites_field_updates_array = explode(', ', $websites_field_updates_string);

//    kint($websites_field_updates_array);

    $edit = FALSE;

    foreach ($websites_field_updates_array as $item) {
      $item = preg_replace("/[^A-Za-z?! ]/","",$item);
      $item = rtrim($item);
//      kint($item);
//      kint($user_terms_name);
      if (in_array($item, $user_terms_name)) {
        $edit = TRUE;
      }
    }

    if ($edit != TRUE) {
      $message = [
        '#theme' => 'item_list',
        '#list_type' => 'ul',
        '#title' => 'One of the following value(s) must exist in the highlighted field',
        '#items' => $user_terms_name,
      ];
//      kint($form_state->getUserInput());
      $form_state->setErrorByName('field_biography_drupal_site_ref', $message);


    }
  }
}