<?php 

/**
 * Implements hook_theme().
 */
/**
function react_router_test_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__react__default' => NULL,
  ];
}
**/


/**
 * Implements hook_preprocess_paragraph().
 */
function react_router_test_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getParagraphType()->id() == 'react') {
    $variables['#attached']['library'][] = 'react_router_test/react_aside_library';
    $variables['#attached']['library'][] = 'react_router_test/react_library';
    $id = $variables['paragraph']->field_root_id->value;
    $variables['content']['field_root_id'][0]['#template'] = "<div id=$id></div>";
  }
}

