<?php

/**
 * @file
 * Contains better_date_range_format.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function better_date_range_format_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the better_date_range_format module.
    case 'help.page.better_date_range_format':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a better way to format date range fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function better_date_range_format_theme() {
  return [
    'better_date_range_format' => [
      'render element' => 'children',
    ],
  ];
}
