<?php

/**
 * @file
 * Contains quikpay_handler.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_help().
 */
function webform_to_node_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the quikpay_handler module.
    case 'help.page.webform_to_node':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom handler for converting webform submissions to nodes') . '</p>';
      return $output;

    default:
  }
}
