<?php
/**
 * User: cheng chen
 * Date: 12/12/19
 * Time: 3:44 PM
 */

namespace Drupal\webform_to_node\Plugin\WebformHandler;
use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Plugin\WebformHandlerBase;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\node\Entity\Node;

/**
 * Form submission handler.
 *
 * @WebformHandler(
 *   id = "webform_to_node",
 *   label = @Translation("Webform submission converter"),
 *   category = @Translation("Form Handler"),
 *   description = @Translation("Convert webform submissions to nodes"),
 *   cardinality =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::CARDINALITY_SINGLE,
 *   results =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::RESULTS_PROCESSED,
 * )
 */
class SubmissionConverterHandler extends WebformHandlerBase {

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state, WebformSubmissionInterface $webform_submission) {

    $field_experiential_full_name = $form_state->getValue('contact_full_name');
    $field_experiential_email_address = $form_state->getValue('contact_email');
    $field_experiential_program_name = $form_state->getValue('program_name');
    $field_experiential_sentence_desc = $form_state->getValue('one_sentence_description');
    $field_experiential_website = $form_state->getValue('experiential_website')['url'];
    $field_experiential_opportunity = $form_state->getValue('opportunity');
    $field_experiential_interest = $form_state->getValue('interest');
    $field_experiential_eligible_stud = $form_state->getValue('eligible');
    $field_experiential_offered = $form_state->getValue('offered');
    $field_experiential_based = $form_state->getValue('where_based');
    $field_experiential_located = $form_state->getValue('where_located');
    $field_experiential_time_commitme = $form_state->getValue('time_commitment');
    $field_experiential_funding = $form_state->getValue('funding');
    $field_experiential_credit = $form_state->getValue('is_credit_available_');
    $field_experiential_additional = $form_state->getValue('additional_information');

    $values = array(
      'field_experiential_email_address' => $field_experiential_email_address,
      'field_experiential_full_name' => $field_experiential_full_name,
      'field_experiential_credit' => $field_experiential_credit,
      'field_experiential_funding' => $field_experiential_funding,
      'field_experiential_additional' => $field_experiential_additional,
      'field_experiential_sentence_desc' => $field_experiential_sentence_desc,
      'field_experiential_website' => $field_experiential_website,
      'field_experiential_time_commitme' => $field_experiential_time_commitme,
      'field_experiential_opportunity' => $field_experiential_opportunity,
      'field_experiential_offered' => $field_experiential_offered,
      'field_experiential_based' => $field_experiential_based,
      'field_experiential_located' => $field_experiential_located,
      'field_experiential_interest' => $field_experiential_interest,
      'field_experiential_eligible_stud' => $field_experiential_eligible_stud,
    );

    $content_type = 'experiential_education_submissio';
    $title = $field_experiential_program_name;
    $langcode = 'en';
    $uid = 1; // superuser
    $status = 0; // unpublish them by default
    // all the variables and their mapping up to this point can be set in the handler config form if needed in future.

    $node = Node::create(array(
        'type' => $content_type,
        'title' => $title,
        'langcode' => $langcode,
        'uid' => $uid,
        'status' => $status,
    ));

    foreach ($values as $key => $value) {
        $node->set($key, $value);
    }

    $result = $node->save();
    if ($result !== 1) {
      \Drupal::logger('webform_to_node')->error('Webform submission to node convertion has failed');
    } else {
      \Drupal::logger('webform_to_node')->info('@title has been created via a webform submission', ['@title' => $title]);
    }
  }
}
