<?php

use Drupal\gin\GinSettings;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Utility\ThemeRegistry;
use Drupal\Core\Session\AccountInterface;


/**
 * Implements hook_page_attachments()
 */
function custom_gin_override_page_attachments(array &$attachments) {
  
    // Get theme settings (optional).
  /** @var \Drupal\gin\GinSettings $settings */
  $settings = \Drupal::classResolver(GinSettings::class);

  // Toolbar example.
  $toolbar = $settings->get('classic_toolbar');

  // Attach the base library if the horizontal toolbar is set.
  if ($toolbar === 'classic') {
    // Attach your library.
    $attachments['#attached']['library'][] = 'custom_gin_override/custom-gin';
    }
  }


  /**
   * Implements hook_form_alter().
   */
  function custom_gin_override_form_alter(&$form, $form_state, $form_id) {
    // Check if it's an entity form.

    if ($form_state->getFormObject() instanceof EntityFormInterface) {
      $route_name = \Drupal::routeMatch()->getRouteName();
      if ($route_name == 'node.add') {
        $form['#attributes']['class'][] = 'form-add';
      } else {
        if ($route_name == 'entity.media.edit_form' || $route_name == 'entity.node.edit_form' ) {
          $form['#attributes']['class'][] = 'form-edit';
        }
      }

      $entity = $form_state->getFormObject()->getEntity();
      $state = $form['moderation_state']['widget'][0]['#type'];
      
      if ($form_id == 'node_robust_3_column_page_form' || $form_id == 'node_robust_3_column_page_edit_form') {
        $form['field_robust_3_page_ref']['widget']['add_more']['#prefix'] = '<div class="no-content">Add new section</div>';
        $form['field_robust_3_page_right_ref']['widget']['add_more']['#prefix'] = '<div class="no-content">Add new section</div>';
      }
      
       // Check if workflow_buttons are enabled for the content type.
      if ($state == 'select') {
     
        if ($entity->isNew()) {
          $form['actions']['#prefix'] = '<div class="actions-desc page-add">Saving options</div>';
        } else {
         if ($entity->isPublished()) {
           $form['actions']['#prefix'] = '<div class="actions-desc">Saving options</div>';
          } 
          else {
            $form['actions']['#prefix'] = '<div class="actions-desc-update"></div>';
         }
        }
         $form['moderation_state']['widget'][0]['#options']['draft'] = 'Save Draft';
      }
    } 


    }

/**
* Implements hook_menu_links_discovered_alter().
*/
function custom_gin_override_menu_links_discovered_alter(&$links) {
  // Adds Main Navigation Menu link in the gin admin toolbar.
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles(); 

  if (!(in_array('school_developer', $roles))) {
    $links['new.main.nav'] = [
    'title' => 'Main Navigation Menu',
    'route_name' => 'entity.menu.edit_form',
    'route_parameters' => ['menu' => 'main'],
    'description' => 'New Main Navigation.',
    'parent' => 'system.admin',
    'weight' => 0,
    ];
   }
  }

/**
* Implements hook_preprocess_HOOK() for page templates.
*/
/*function custom_gin_override_preprocess_page(array &$variables) {
// Get the current user.
$current_user = \Drupal::currentUser();



// Check if the user is authenticated.
if ($current_user->isAuthenticated()) {
// Create the banner message markup.
$banner_markup = '
<div class="access-banner">
<div>Digital Accessibility Training</div>
All Drupal users must complete
<a href="https://canvas.case.edu/enroll/JLMY7D" style="color: #000000" target="_blank">Digital Accessibility training</a>.
If you haven\'t completed the course by Oct. 31, your editing access will be temporarily suspended until you can do so.
</div>';



// Get the current path.
$current_path = \Drupal::service('path.current')->getPath();



// Check if the current path is an admin page.
if (preg_match('~^/admin~', $current_path)) {

if (isset($variables['page']['breadcrumb']['#markup'])) {
// Prepend the banner message to existing markup.
$variables['page']['breadcrumb']['#markup'] = $banner_markup . $variables['page']['breadcrumb']['#markup'];
} else {
// If no existing markup, just set the banner.
$variables['page']['breadcrumb']['#markup'] = $banner_markup;
}



} else {



if (isset($variables['page']['header']['#markup'])) {
// Prepend the banner message to existing markup.
$variables['page']['rave_region']['#markup'] = $banner_markup . $variables['page']['rave_region']['#markup'];
} else {
// If no existing markup, just set the banner.
$variables['page']['rave_region']['#markup'] = $banner_markup;
}
}



}
}
*/
