<?php

namespace Drupal\labs_custom_blocks\Plugin\views\filter;

use Drupal\Core\Session\AccountProxyInterface;
use Drupal\views\Plugin\views\filter\FilterPluginBase;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Filter by current user's sites term
 *
 * @ingroup views_filter_handlers
 * @ViewsFilter("restrict_term_display")
 */
class RestrictTermDisplay extends FilterPluginBase {
  protected AccountProxyInterface $currentUser;

  /**
   *
   * @var object $userSitesInfo
   */
  protected object $userSitesInfo;

  public function __construct(array $configuration, $plugin_id, $plugin_definition, AccountProxyInterface $currentUser, $userSitesInfo) {
    parent::__construct($configuration, $plugin_id, $plugin_definition);
    $this->currentUser = $currentUser;
    $this->userSitesInfo = $userSitesInfo;
  }

  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('current_user'),
      $container->get('labs_custom_blocks.get_user_site_info')
    );
  }

  /**
   * {@inheritdoc}
   */
  public function query() : void {
    //parent::query(); // TODO: Change the autogenerated stub
    if (\Drupal::currentUser()->isAuthenticated() && !$this->currentUser->hasRole('administrator')) {
      $this->ensureMyTable();
      if (!empty($this->userSitesInfo->getCurrentUserTermIds())) {
        $this->query->addWhere($this->options['group'], 'taxonomy_term_field_data.tid', $this->userSitesInfo->getCurrentUserTermIds(), 'IN');
      } else {
        // set a false condition so nothing is displayed.
        $this->query->addWhere($this->options['group'], 'taxonomy_term_field_data.tid', '0', '=');
      }
    }
  }
}
