<?php

namespace Drupal\labs_custom_blocks\Plugin\views\filter;

use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\views\Plugin\views\filter\FilterPluginBase;
use Drupal\Core\Session\AccountProxyInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Filter by current node's sites term
 *
 * @ingroup views_filter_handlers
 * @ViewsFilter("restrict_biography_display")
 */
class RestrictBioDisplay extends FilterPluginBase implements ContainerFactoryPluginInterface {

  protected AccountProxyInterface $currentUser;

  public function __construct(array $configuration, $plugin_id, $plugin_definition, AccountProxyInterface $currentUser, $userSitesInfo) {
    parent::__construct($configuration, $plugin_id, $plugin_definition);
    $this->currentUser = $currentUser;
    $this->userSitesInfo = $userSitesInfo;
  }

  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition): void {
    // TODO: Implement create() method.
    $container->get('current_user');
    $container->get('labs_custom_blocks.get_user_site_info');
  }

  /**
   *
   * @var object $userSitesInfo
   */
  protected object $userSitesInfo;

  /**
   * {@inheritdoc}
   */
  public function query(): void {
    //parent::query(); // TODO: Change the autogenerated stub
    if (\Drupal::currentUser()->isAuthenticated() && !$this->currentUser->hasRole('administrator') && !empty($this->userSitesInfo->getCurrentUserTermIds())) {
      $this->ensureMyTable();
      $this->query->addWhere($this->options['group'], 'node__field_biography_drupal_site_ref.field_biography_drupal_site_ref_target_id', $this->userSitesInfo->getCurrentUserTermIds(), 'IN');
    }
  }
}
