<?php
/**
 * User: chulavista
 * Date: 8/12/19
 * Time: 3:44 PM
 */

namespace Drupal\quikpay_handler\Plugin\WebformHandler;

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\webform\Plugin\WebformHandlerBase;
use Drupal\webform\WebformSubmissionInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;

/**
 * Form submission handler.
 *
 * @WebformHandler(
 *   id = "quikpay_form_handler",
 *   label = @Translation("QuikPay Webform Handler"),
 *   category = @Translation("Form Handler"),
 *   description = @Translation("Generate string and redirect to QuikPay"),
 *   cardinality =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::CARDINALITY_SINGLE,
 *   results =
 *   \Drupal\webform\Plugin\WebformHandlerInterface::RESULTS_PROCESSED,
 * )
 */
class QuikpayHandler extends WebformHandlerBase {

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    $form['amountDue'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Amount Due'),
      '#description' => $this->t('If the amount due is a static number, please specify it here'),
      '#default_value' => $this->configuration['amountDue'],
    ];

    $form['test_mode'] = [
      '#type' => 'radios',
      '#title' => $this->t('Test mode?'),
      '#default_value' => $this->configuration['test_mode'],
      '#options' => [
        'no' => $this->t('No'),
        'yes' => $this->t('Yes'),
      ],
    ];

    $form['ordertype'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Order Type for Quikpay'),
      '#description' => $this->t('OrderType value, from Controller\'s office '),
      '#default_value' => $this->configuration['ordertype'],
      '#required' => TRUE,
    ];

    $form['quikpay_url'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Prod URL for Quikpay'),
      '#description' => $this->t('Prod URL for Quikpay redirect'),
      '#default_value' => $this->configuration['prod_url'],
      '#required' => TRUE,
    ];


    $form['prod_key'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Prod key for Quikpay'),
      '#description' => $this->t('Prod key for Quikpay redirect'),
      '#default_value' => $this->configuration['prod_key'],
      '#required' => TRUE,
    ];

    $form['test_key'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Test key for Quikpay'),
      '#description' => $this->t('Test key for Quikpay redirect'),
      '#default_value' => $this->configuration['test_key'],
      '#required' => FALSE,
    ];

    $form['redirect_url'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Redirect URL for Quikpay'),
      '#description' => $this->t('Redirect URL from Quikpay'),
      '#default_value' => $this->configuration['redirect_url'],
      // '#required' => TRUE,
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function defaultConfiguration() {
    return [
      'prod_url' => 'https://quikpayasp.com/cwru2/commerce_manager/payer.do',
      'prod_key' => 'an458AN5d9uHy1m67qF3UI3456GCTj',
      'test_url' => 'https://uatquikpayasp.com/cwru2/commerce_manager/payer.do',
      'test_key' => 'gotribe',
    ];
  }


  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state); // TODO: Change the autogenerated stub
    $this->configuration['ordertype'] = $form_state->getValue('ordertype');
    $this->configuration['test_mode'] = $form_state->getValue('test_mode');
    $this->configuration['redirect_url'] = $form_state->getValue('redirect_url');
    $this->configuration['amountDue'] = $form_state->getValue('amountDue');
    $this->configuration['prod_key'] = $form_state->getValue('prod_key');
    $this->configuration['test_key'] = $form_state->getValue('test_key');
  }


  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state, WebformSubmissionInterface $webform_submission) {

    //  shared from attributes
    $orderType = $this->configuration['ordertype'];
    $testKey = $this->configuration['test_key'];
    $orderNumber = round(microtime(TRUE) * 1000);
    $timestamp = round(microtime(TRUE) * 1000);
    $static_amount = $this->configuration['amountDue'] ?: NULL;
    if (!empty($webform_submission->getElementData('total'))) {
      if (is_numeric($webform_submission->getElementData('total'))) {
        $dynamic_amount = $webform_submission->getElementData('total');
      }
      else {
        $dynamic_amount = str_replace('$', '', trim($webform_submission->getElementData('total')
          ->__toString()));
      }
      $dynamic_amount = $dynamic_amount + 0;
    }
    $amountDue = $static_amount ?? $dynamic_amount * 100;

    $redirectUrl = $this->configuration['redirect_url'];
    $retriesAllowed = 3;
    $redirectUrlParameters = "transactionType,transactionStatus,transactionId,transactionTotalAmount,transactionDate,transactionAcountType,transactionDescription,orderType,payerFullName,accountHolderName,email,userChoice3";

    $userChoice3 = $orderNumber;
    $webform_submission->setElementData('order_number', $orderNumber);

    // set a session variable to prevent session manipulation
    //$session = \Drupal::request()->getSession();
    //$session->set('quikpay_session', $orderNumber);

    $tsf = \Drupal::service('session_based_temp_store');
    $ts = $tsf->get('qp');
    $ts->set($orderNumber, $orderNumber);

    //  test/prod switch
    switch ($this->configuration['test_mode']) {
      case 'yes':
        $secret = $testKey;
        if (!empty($redirectUrl)) {
          $hash = md5($orderNumber . $orderType . $amountDue . $userChoice3 . $redirectUrl . $redirectUrlParameters . $retriesAllowed . $timestamp . $secret);
          $redirect_url = "https://uatquikpayasp.com/cwru2/commerce_manager/payer.do?orderNumber=$orderNumber&orderType=$orderType&amountDue=$amountDue&userChoice3=$orderNumber&redirectUrl=$redirectUrl&redirectUrlParameters=$redirectUrlParameters&retriesAllowed=$retriesAllowed&timestamp=$timestamp&hash=$hash";
        }
        else {
          $hash = md5($orderNumber . $orderType . $amountDue . $userChoice3 . $retriesAllowed . $timestamp . $secret);
          $redirect_url = "https://uatquikpayasp.com/cwru2/commerce_manager/payer.do?orderNumber=$orderNumber&orderType=$orderType&amountDue=$amountDue&userChoice3=$orderNumber&retriesAllowed=$retriesAllowed&timestamp=$timestamp&hash=$hash";
        }
        break;
      case 'no':
        $secret = $this->configuration['prod_key'];
        if (!empty($redirectUrl)) {
          $hash = md5($orderNumber . $orderType . $amountDue . $userChoice3 . $redirectUrl . $redirectUrlParameters . $retriesAllowed . $timestamp . $secret);
          $redirect_url = "https://quikpayasp.com/cwru2/commerce_manager/payer.do?orderNumber=$orderNumber&orderType=$orderType&amountDue=$amountDue&userChoice3=$orderNumber&redirectUrl=$redirectUrl&redirectUrlParameters=$redirectUrlParameters&retriesAllowed=$retriesAllowed&timestamp=$timestamp&hash=$hash";
        }
        else {
          $hash = md5($orderNumber . $orderType . $amountDue . $userChoice3 . $retriesAllowed . $timestamp . $secret);
          $redirect_url = "https://quikpayasp.com/cwru2/commerce_manager/payer.do?orderNumber=$orderNumber&orderType=$orderType&amountDue=$amountDue&userChoice3=$orderNumber&retriesAllowed=$retriesAllowed&timestamp=$timestamp&hash=$hash";
        }
        break;
    }
    $url = Url::fromUri($redirect_url);
    $destination = $url->toString();
    $redirect = new TrustedRedirectResponse($destination);
    $redirect->send();

    return TRUE;
  }

}

