<?php

/**
 * @file
 * Contains cwru_custom_webform_validations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cwru_custom_webform_validations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cwru_custom_webform_validations module.
    case 'help.page.cwru_custom_webform_validations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a central place to hold all webform validations') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_webform_element_alter().
 */
function cwru_custom_webform_validations_webform_element_alter(array &$element, \Drupal\Core\Form\FormStateInterface $form_state, array $context) {
  // EMS site START.
  $requesturi = \Drupal::request()->getRequestUri();
  $requesturi = explode('/', $requesturi, 3);

  if ($requesturi[1] == 'ems') {
    if (isset($element['#webform_id']) && $element['#webform_id'] === 'feedback_form--form_recipients') {
      $element['#element_validate'][] = array(
        'Drupal\cwru_custom_webform_validations\Plugin\Validation\RecipientConstraint',
        'countValidate'
      );
    }
  }
  // EMS site END.


}