<?php

/**
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_theme_suggestions_alter.
 */
function crew_holoanatomy_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);
  if ($path_alias == '/about/contact') {
    $suggestions[] = $hook . '__' . 'contact';
  }
}
